name = "nbidal18 Vanilla+ Hardcore"
version = "1.0.1"
description = "Minecraft 26.2 vanilla+ modpack with automatic Prism updates"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb0ef61acbc985b053ab43e11fa533644d54f23468f84b349831c3fdbe1f5b76"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
