name = "nbidal18 Vanilla+ Hardcore"
version = "1.0.0"
description = "Minecraft 26.2 vanilla+ modpack with automatic Prism updates"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "851440a3b9afdc0ffafdd43ae3e36d761c102c75472b7702475efd18641f7bed"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
