#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 23 23:18:44 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=nbidal18-Eclipse-Shader-Unstable.zip
