version = 1

	[mixin.perf]
		#Replace buildSurface with optimized implementation
		#default: true
		#incompatibleWith: biolith
		surface = true
		#Replace populateNoise with optimized implementation
		#default: true
		noise = true
		#Replace populateBiomes with optimized implementation
		#default: true
		biome = true

	[perf.surface]
		#Predict biomes in advance in surface builder. Major speedup for surface builder
		# (depends on surface builder mixin)
		#default: true
		biome = true
		#Skip trivial surface builder. Major speedup for end dimension. Depends on surface builder
		# (depends on surface builder mixin)
		#default: true
		trivial = true

	[perf.biomes]
		#Optimize biome tree by avoiding multiple calls to thread local
		#default: false
		#incompatibleWith: biolith
		tree = false
		#Optimize end biome generation (2x speed) but may cause mod incompatibility
		#default: true
		#incompatibleWith: biolith
		end = true
		#Optimize single biome generation (major speedup) but may cause mod incompatibility
		#default: true
		fixed = true
