<#
    Writes down what is actually installed on the live server.

      scripts\Export-ServerInventory.ps1

    Nothing else in this repository records it. The client pack is versioned in full, the channel is
    verifiable against the build, and the server - the thing players actually connect to - existed
    only as jars on an SFTP mount. Losing that drive meant rebuilding it from memory.

    **That drive is exactly what was then lost.** This read `Y:`, a CloudMounter mount whose trial
    expired, so it threw on every run afterwards and the inventory silently stopped being updated -
    still describing 46 mods and a login mod that had been removed, while the server ran 67. It now
    pulls the same mirror the deploy uses, over SFTP, with no drive letter involved.

    The output goes to the release folder, not to site\, so it is never published and never moves
    the manifest digest.

    Deliberately NOT recorded: whitelist and ops contents. This repository is public, and those are
    player names and UUIDs. Counts only.

    Read-only. It touches nothing on the server, so it is safe while the server is running.
#>
[CmdletBinding()]
param(
    # The local mirror of the server. Defaults to the one Sync-ServerMirror keeps.
    [string] $DriveRoot,
    # Skip the pull and read the mirror as it stands. Only when it was refreshed moments ago -
    # otherwise this writes down a server that has moved on, which is worse than writing nothing.
    [switch] $SkipPull,
    [string] $Session = $env:NBIDAL18_WINSCP_SESSION
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repo = Split-Path -Parent $PSScriptRoot
$version = (Get-Content -LiteralPath (Join-Path $repo 'PACK-VERSION.txt') -Raw).Trim()
$prefix = & (Join-Path $PSScriptRoot 'ReleaseLine.ps1')
$release = Join-Path (Split-Path -Parent $repo) "$prefix$version"
$clientMods = Join-Path $release '3. modpack\client\mods'
$out = Join-Path $release '4. server\SERVER-INVENTORY.md'

$mirrorDefault = Join-Path (Split-Path -Parent $repo) '_server-payload-cache'
if (-not $DriveRoot) { $DriveRoot = $mirrorDefault }
$syncScript = Join-Path $PSScriptRoot 'Sync-ServerMirror.ps1'

if (-not $SkipPull) {
    Write-Host 'pull      refreshing the mirror from the live server'
    & $syncScript -Pull -Session $Session -MirrorRoot $DriveRoot | Out-Null
}
if (-not (Test-Path -LiteralPath $DriveRoot)) { throw "No mirror of the server at $DriveRoot" }

# whitelist.json and ops.json are live player state rather than deployable payload, so the mirror
# does not carry them and they are fetched on their own. Only their counts are written down - see
# the note above about this repository being public.
$aside = Join-Path $env:TEMP ('nbidal18-inventory-' + [Guid]::NewGuid())
New-Item -ItemType Directory -Force -Path $aside | Out-Null
foreach ($name in @('whitelist.json', 'ops.json')) {
    & $syncScript -Get $name -To (Join-Path $aside $name) -Session $Session -MirrorRoot $DriveRoot | Out-Null
}

$clientNames = @(Get-ChildItem -LiteralPath $clientMods -Filter *.jar | ForEach-Object { $_.Name })
$serverMods = @(Get-ChildItem -LiteralPath (Join-Path $DriveRoot 'mods') -Filter *.jar | Sort-Object Name)
$serverOnly = @($serverMods | Where-Object { $clientNames -notcontains $_.Name })
$shared = $serverMods.Count - $serverOnly.Count
$clientOnly = @($clientNames | Where-Object { $n = $_; -not ($serverMods | Where-Object { $_.Name -eq $n }) })

function Get-Sha([string] $path) {
    return (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLower()
}

# server.properties, minus the keys that are vanilla defaults, so the list is what was chosen.
$props = [ordered]@{}
foreach ($line in ([IO.File]::ReadAllText((Join-Path $DriveRoot 'server.properties')) -split "`r?`n")) {
    if ($line -match '^([a-z][a-z0-9.\-]*)=(.*)$') { $props[$Matches[1]] = $Matches[2] }
}
$interesting = 'hardcore', 'difficulty', 'online-mode', 'white-list', 'enforce-whitelist', 'max-players',
'view-distance', 'simulation-distance', 'pause-when-empty-seconds', 'server-port', 'level-name',
'motd', 'allow-flight', 'spawn-protection', 'enable-rcon', 'enable-query'

$md = New-Object Text.StringBuilder
function Add([string] $line = '') { $null = $md.AppendLine($line) }

Add "# What is on the server"
Add ''
Add "Generated by ``scripts\Export-ServerInventory.ps1`` for **v$version**. Do not edit by hand."
Add ''
Add "The client pack is versioned in full and the channel is verifiable against the build. This file"
Add "is the equivalent record for the server, which is otherwise only an SFTP mount."
Add ''
Add "Whitelist and ops contents are deliberately omitted - this repository is public and those are"
Add "player names and UUIDs. Counts only."
Add ''

Add "## Launcher"
Add ''
$serverJar = Join-Path $DriveRoot 'server.jar'
Add "| | |"
Add "| --- | --- |"
Add ("| ``server.jar`` | {0} bytes, sha256 ``{1}`` |" -f (Get-Item -LiteralPath $serverJar).Length, (Get-Sha $serverJar).Substring(0, 16))
Add ("| Minecraft | {0} |" -f (Get-Content -LiteralPath (Join-Path $repo 'MINECRAFT.txt') -Raw).Trim())
Add ("| Fabric loader | {0} |" -f (Get-Content -LiteralPath (Join-Path $repo 'LOADER.txt') -Raw).Trim())
Add ''
Add "It is the Fabric installer's ``ServerLauncher``, not the Minecraft server, and **it must carry no"
Add "jar signature** - leaving ``META-INF/*.SF`` and ``.RSA`` in place makes ``JarVerifier`` reject it"
Add "before the main class loads."
Add ''

Add "## Settings that were chosen"
Add ''
Add "| Key | Value |"
Add "| --- | --- |"
foreach ($k in $interesting) { if ($props.Contains($k)) { Add ("| ``{0}`` | ``{1}`` |" -f $k, $props[$k]) } }
Add ''
Add ("Voice chat listens on UDP **{0}**." -f ((Select-String -LiteralPath (Join-Path $DriveRoot 'config\voicechat\voicechat-server.properties') -Pattern '^port=(.+)$').Matches[0].Groups[1].Value))
Add ''
Add ("Whitelist holds **{0}** players, ops **{1}**." -f `
    ((Get-Content -LiteralPath (Join-Path $aside 'whitelist.json') -Raw | ConvertFrom-Json) | Measure-Object).Count, `
    ((Get-Content -LiteralPath (Join-Path $aside 'ops.json') -Raw | ConvertFrom-Json) | Measure-Object).Count)
Add ''

Add "## Mods"
Add ''
Add ("**{0} on the server.** {1} are the same jar as the client pack ships; **{2} exist only here.**" -f `
        $serverMods.Count, $shared, $serverOnly.Count)
Add ''
Add "The client pack is the source for every shared jar - a server jar that is not byte-identical to"
Add "the client's copy is a deployment mistake, not a variant."
Add ''
Add "### Server-only"
Add ''
Add "| Mod | Size | sha256 | Why it is here |"
Add "| --- | --- | --- | --- |"
$why = @{
    'spark'         = 'Profiler. Its background profiler is why a report can cover the period before anyone noticed a problem.'
    'easywhitelist' = 'Whitelist by name, which is what an offline-mode server has to go on.'
}
foreach ($m in $serverOnly) {
    $key = ($why.Keys | Where-Object { $m.Name -like "$_*" } | Select-Object -First 1)
    Add ("| ``{0}`` | {1:N0} B | ``{2}`` | {3} |" -f $m.Name, $m.Length, (Get-Sha $m.FullName).Substring(0, 16),
        $(if ($key) { $why[$key] } else { '**Undocumented - say why, or remove it.**' }))
}
Add ''
Add "### Shared with the client pack"
Add ''
Add "<details><summary>$shared jars</summary>"
Add ''
Add "| Mod | sha256 | Matches the client pack |"
Add "| --- | --- | --- |"
foreach ($m in ($serverMods | Where-Object { $clientNames -contains $_.Name })) {
    $clientCopy = Join-Path $clientMods $m.Name
    $same = (Get-Sha $clientCopy) -eq (Get-Sha $m.FullName)
    Add ("| ``{0}`` | ``{1}`` | {2} |" -f $m.Name, (Get-Sha $m.FullName).Substring(0, 16),
        $(if ($same) { 'yes' } else { '**NO - redeploy it**' }))
}
Add ''
Add "</details>"
Add ''
Add "### In the client pack and not on the server"
Add ''
Add ("**{0} jars.** Client-rendering, UI and input mods a server has no use for." -f $clientOnly.Count)
Add ''
Add "The one to be careful with is Voxy: ``voxy`` is the client renderer and belongs only on the"
Add "client, but **``Voxy World Gen V2`` is ``environment: `"*`"`` and belongs on both** - the server"
Add "generates the chunks and streams LOD, the client renders it. It was left off the server once on"
Add "the assumption that anything named Voxy is client-side."
Add ''

Add "## Config"
Add ''
$serverConfigs = @(Get-ChildItem -LiteralPath (Join-Path $DriveRoot 'config') -Recurse -File | Sort-Object FullName)
Add ("**{0} files.** Only the ones below are server-authored or server-specific; the rest arrive with the mods." -f $serverConfigs.Count)
Add ''
Add "| File | Note |"
Add "| --- | --- |"
Add "| ``nbidal18-integrity.properties`` | **Generated by the build.** Carries ``expected-manifest-sha256``. Deployed by ``Deploy-LiveServer.ps1``, never edited |"
Add "| ``voicechat/voicechat-server.properties`` | Voice chat port and ranges |"
Add "| ``easywhitelist.json`` or equivalent | Whitelist backing store |"
Add "| ``spark/`` | Profiler settings |"
Add "| ``voxyworldgenv2.json`` | ``generationRadius`` - the server half of Voxy |"
Add ''

Add "## Rebuilding this server from nothing"
Add ''
Add "1. Fabric ``ServerLauncher`` as ``server.jar``, with ``install.properties`` naming the loader and game version, and **no jar signature**"
Add "2. ``eula.txt``, then ``server.properties`` with the settings above - **never copied wholesale from the 1.21.1 server**, which carries its own ports, level name and a datapack list that does not exist here"
Add "3. The shared jars, taken from the client pack of the matching release"
Add "4. The server-only jars above"
Add "5. ``server-icon.png`` - without it the server falls back to the world's own ``icon.png``, which is a screenshot"
Add "6. The world, then ``Deploy-LiveServer.ps1 -Apply`` for the policy, helper and MOTD"
Add ''

New-Item -ItemType Directory -Force -Path (Split-Path $out -Parent) | Out-Null
[IO.File]::WriteAllText($out, $md.ToString(), (New-Object Text.UTF8Encoding($false)))

Write-Host ("mods      {0} on the server: {1} shared, {2} server-only, {3} client-only" -f $serverMods.Count, $shared, $serverOnly.Count, $clientOnly.Count)
$mismatched = @($serverMods | Where-Object { $clientNames -contains $_.Name } | Where-Object { (Get-Sha (Join-Path $clientMods $_.Name)) -ne (Get-Sha $_.FullName) })
if ($mismatched.Count) {
    Write-Host ("MISMATCH  {0} shared jars differ from the client pack: {1}" -f $mismatched.Count, (($mismatched | ForEach-Object { $_.Name }) -join ', '))
}
else { Write-Host 'match     every shared jar is byte-identical to the client pack' }
Write-Host ("config    {0} files" -f $serverConfigs.Count)
Write-Host ("wrote     {0}" -f $out)

# Player names and UUIDs, which is why only their counts were written down. They do not linger.
Remove-Item -LiteralPath $aside -Recurse -Force -ErrorAction SilentlyContinue
