<#
.SYNOPSIS
    Generate the same seed twice - once with a mod, once without - and compare the chunks byte for
    byte.

.DESCRIPTION
    Written 2026-09-22 for the malformed End City ships. The owner reports ships with blocks missing,
    and confirmed the damage is **not** aligned to chunk borders. Six mods touch End City placement in
    this pack; five were read and cleared, leaving C2ME `0.4.1-beta.1.0` - a beta doing chunk
    threading, mixed into `StructurePiece`, `StructureStart`, `StructureTemplate`, `ProtoChunk`,
    `ChunkStatus`, `WorldGenRegion` and `Beardifier`.

    **The test does not depend on finding a ship.** C2ME is a pure optimisation: it promises the same
    world, generated faster. **So identical seeds must give identical region files.** Any difference
    at all is C2ME changing worldgen output, which is the property the End City suspicion rests on -
    and it is far cheaper to measure than hunting a structure.

    Each run stages the release's server payload into a throwaway directory, boots with a fixed seed,
    waits for "Done", asks the server to save, stops it cleanly over stdin, and hashes every region
    file. The two runs are then compared.

    A difference proves C2ME alters generation. **No difference does not clear it** - the End is not
    generated at spawn, and a threading fault may only show under load - but it is the cheap half of
    the answer and it runs unattended.

.PARAMETER RemoveMods
    Jar name patterns withheld from the SECOND run. Defaults to C2ME.

.PARAMETER Seed
    The level seed both runs use. Any fixed value does; it is recorded in the output.

.EXAMPLE
    .\Test-WorldgenParity.ps1
    .\Test-WorldgenParity.ps1 -RemoveMods 'c2me*','lithostitched*' -Seed 12345
#>
[CmdletBinding()]
param(
    [string[]] $RemoveMods = @('c2me*'),
    [long] $Seed = 8675309,
    [int] $BootTimeoutSeconds = 420,
    [int] $MinecraftPort = 29160,
    # How much world each run generates, as a radius in chunks around spawn. A booted server with no
    # player generates almost nothing on its own; 16 gives a 33x33 area, about a thousand chunks,
    # which is a sample worth comparing.
    [int] $ForceloadRadiusChunks = 16,
    [int] $GenerateSeconds = 120,
    # Withhold the mods from BOTH runs instead of only the second. This turns the script into a
    # determinism check for the remaining mod set: two identical runs that still differ mean
    # generation is not reproducible at all, and no comparison against a withheld mod can mean
    # anything until that is understood.
    [switch] $WithholdFromBoth,
    # Which dimension to generate and compare. The End is the dimension the malformed-ship report is
    # about, and it is NOT generated by a server sitting at overworld spawn - forceload is per
    # dimension, so an overworld-only run says nothing about End City placement.
    [string] $Dimension = 'minecraft:overworld',
    # Where to centre the generated area, in chunks. End Cities only exist on the outer End islands,
    # past x=1024 blocks from the centre, so an End run has to be offset or it generates the main
    # island and finds nothing.
    [int] $CenterChunkX = 0,
    [int] $CenterChunkZ = 0,
    [switch] $KeepDirs
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repo = Split-Path -Parent $PSScriptRoot
$version = (Get-Content -LiteralPath (Join-Path $repo 'PACK-VERSION.txt') -Raw).Trim()
$prefix = & (Join-Path $PSScriptRoot 'ReleaseLine.ps1')
$release = Join-Path (Split-Path -Parent $repo) "$prefix$version"
# The SERVER's mod set, from the mirror - not the client's. Staging all 173 client jars loaded 295
# mods and crashed the tick loop within seconds: Xaero's Minimap registers `xaerominimap:main`
# twice when its client jar is present server-side ("Packet type ... is already registered"). Every
# run before this one crashed that way, which is why they compared half-generated worlds.
$mirror = Join-Path (Split-Path -Parent $repo) '_server-payload-cache'
$serverMods = Join-Path $mirror 'mods'
$clientConfig = Join-Path $mirror 'config'
$javaPath = Join-Path $env:APPDATA 'PrismLauncher\java\java-runtime-epsilon\bin\java.exe'
foreach ($required in @($serverMods, $clientConfig, $javaPath)) {
    if (-not (Test-Path -LiteralPath $required)) { throw "Missing input: $required" }
}

# A server-side jar is one that is not client-only. The release's own deploy logic makes this
# distinction by reading each jar's environment; here the simpler rule is enough, because a
# client-only jar on a dedicated server is ignored rather than fatal.
function Copy-Payload([string] $target, [string[]] $withhold) {
    New-Item -ItemType Directory -Path (Join-Path $target 'mods') -Force | Out-Null
    $skipped = @()
    foreach ($jar in Get-ChildItem -LiteralPath $serverMods -Filter *.jar -File) {
        $drop = $false
        foreach ($pattern in $withhold) { if ($jar.Name -like $pattern) { $drop = $true } }
        # The integrity helper enforces the published channel; a throwaway server has none.
        if ($jar.Name -like 'nbidal18-integrity-*.jar') { $drop = $true }
        if ($drop) { $skipped += $jar.Name; continue }
        Copy-Item -LiteralPath $jar.FullName -Destination (Join-Path $target 'mods') -Force
    }
    if (Test-Path -LiteralPath $clientConfig) {
        Copy-Item -LiteralPath $clientConfig -Destination (Join-Path $target 'config') -Recurse -Force
    }
    return $skipped
}

function Invoke-Run([string] $label, [string[]] $withhold) {
    $root = Join-Path ([IO.Path]::GetTempPath()) "nbidal18-parity-$label"
    if (Test-Path -LiteralPath $root) { Remove-Item -LiteralPath $root -Recurse -Force }
    New-Item -ItemType Directory -Path $root | Out-Null

    # @() around the call: an empty array returned from a function collapses to $null, and
    # StrictMode then fails on .Count.
    $skipped = @(Copy-Payload $root $withhold)
    Write-Host ("[{0}] payload staged, {1} jar(s) withheld{2}" -f $label, $skipped.Count,
        $(if ($skipped.Count) { ': ' + ($skipped -join ', ') } else { '' }))

    [IO.File]::WriteAllText((Join-Path $root 'eula.txt'), "eula=true`n")
    $props = @(
        "level-seed=$Seed"
        "server-port=$MinecraftPort"
        'online-mode=false'
        'white-list=false'
        'spawn-protection=0'
        'view-distance=10'
        'simulation-distance=10'
        'max-players=1'
        'sync-chunk-writes=true'   # so the comparison reads what was generated, not a partial flush
        'level-name=world'
    ) -join "`n"
    [IO.File]::WriteAllText((Join-Path $root 'server.properties'), $props + "`n")

    # A datapack that force-loads the test area the moment the world loads. /forceload takes at most
    # 256 chunks per call, so the area is issued as bands of whole rows that stay under that.
    $chunks = [int] $ForceloadRadiusChunks
    $width = $chunks * 2 + 1
    $band = [Math]::Max(1, [Math]::Floor(256 / $width))
    # Everything that changes a block AFTER generation has to be switched off, or the comparison is
    # measuring the clock rather than worldgen. The run that discovered this compared two runs of an
    # IDENTICAL mod set and found 488 of 2601 chunks differing - and every one of them sat inside the
    # loaded ring, where random ticks, water, fire and mob spawning had kept editing blocks for five
    # minutes. Outside that ring all 1712 chunks were byte-identical. Worldgen was never the variable.
    $lines = @(
        'gamerule randomTickSpeed 0'
        'gamerule doFireTick false'
        'gamerule doMobSpawning false'
        'gamerule doMobGriefing false'
        'gamerule doPatrolSpawning false'
        'gamerule doTraderSpawning false'
        'gamerule doWeatherCycle false'
        'gamerule doDaylightCycle false'
        # A datapack function runs as a silent source, so nothing it does appears in the log. Without
        # these two a refused forceload is indistinguishable from a successful one.
        'gamerule sendCommandFeedback true'
        'gamerule logAdminCommands true'
    )
    for ($cz = $CenterChunkZ - $chunks; $cz -le $CenterChunkZ + $chunks; $cz += $band) {
        $zTo = [Math]::Min($cz + $band - 1, $CenterChunkZ + $chunks)
        $x0 = ($CenterChunkX - $chunks) * 16
        $x1 = ($CenterChunkX + $chunks) * 16 + 15
        $lines += "execute in $Dimension run forceload add $x0 $($cz * 16) $x1 $($zTo * 16 + 15)"
    }
    $packRoot = Join-Path $root 'world\datapacks\nbidal18-parity'
    $fnDir = Join-Path $packRoot 'data\nbidal18_parity\function'
    New-Item -ItemType Directory -Path $fnDir -Force | Out-Null
    New-Item -ItemType Directory -Path (Join-Path $packRoot 'data\minecraft\tags\function') -Force | Out-Null
    $utf8 = New-Object Text.UTF8Encoding($false)
    [IO.File]::WriteAllText((Join-Path $fnDir 'load.mcfunction'), ($lines -join "`n") + "`n", $utf8)
    [IO.File]::WriteAllText((Join-Path $packRoot 'pack.mcmeta'),
        '{"pack":{"pack_format":88,"description":"worldgen parity harness"}}', $utf8)
    [IO.File]::WriteAllText((Join-Path $packRoot 'data\minecraft\tags\function\load.json'),
        '{"values":["nbidal18_parity:load"]}', $utf8)
    Write-Host ("[{0}] datapack will forceload {1}x{1} chunks of {2} in {3} call(s)" -f $label, $width, $Dimension, ($lines.Count - 10))

    # The same launcher Test-DedicatedServer uses: the live server's own server.jar from the mirror,
    # a Fabric launcher that fetches the game and the loader on first run.
    $mirror = Join-Path (Split-Path -Parent $repo) '_server-payload-cache'
    $launcher = Join-Path $mirror 'server.jar'
    if (-not (Test-Path -LiteralPath $launcher)) { throw "No server.jar in the mirror: $launcher" }
    Copy-Item -LiteralPath $launcher -Destination (Join-Path $root 'server.jar') -Force
    # Reuse the game and loader the mirror already holds, so neither run downloads anything and both
    # run against identical bytes.
    foreach ($shared in 'libraries', 'versions') {
        $source = Join-Path $mirror $shared
        if (Test-Path -LiteralPath $source) {
            Copy-Item -LiteralPath $source -Destination (Join-Path $root $shared) -Recurse -Force
        }
    }

    $psi = New-Object Diagnostics.ProcessStartInfo
    $psi.FileName = $javaPath
    $psi.Arguments = '-Xmx4G -jar server.jar nogui'
    $psi.WorkingDirectory = $root
    # ONLY stdin is redirected. A redirected stdout that nobody drains fills its pipe buffer and the
    # server blocks on its next write - which is what made two earlier runs generate a single chunk
    # while reporting success. Draining it from a PowerShell event handler did not work either.
    # Minecraft writes logs\latest.log regardless, so progress is read from there and the pipe
    # problem disappears entirely.
    $psi.RedirectStandardInput = $true
    $psi.RedirectStandardOutput = $false
    $psi.RedirectStandardError = $false
    $psi.UseShellExecute = $false
    $server = [Diagnostics.Process]::Start($psi)
    # StandardInput is a buffered StreamWriter. Without this every command sits in the buffer and
    # the server never sees it - which is exactly what "forceload acks: 0" was reporting while the
    # run still looked successful.
    $server.StandardInput.AutoFlush = $true
    # .NET's default console encoding writes a UTF-8 BOM on the FIRST line only, and the server sees
    # it as part of the command: the log showed `Unknown or incomplete command ... ﻿save-all flush`.
    # Writing through the base stream with a BOM-less encoder keeps the first command intact.
    $stdin = New-Object IO.StreamWriter($server.StandardInput.BaseStream, (New-Object Text.UTF8Encoding($false)))
    $stdin.AutoFlush = $true

    $logPath = Join-Path $root 'logs\latest.log'
    function Read-Log {
        if (-not (Test-Path -LiteralPath $logPath)) { return '' }
        $stream = [IO.File]::Open($logPath, 'Open', 'Read', 'ReadWrite')
        try { return (New-Object IO.StreamReader($stream)).ReadToEnd() } finally { $stream.Dispose() }
    }

    $deadline = (Get-Date).AddSeconds($BootTimeoutSeconds)
    $done = $false
    while ((Get-Date) -lt $deadline -and -not $server.HasExited) {
        if ((Read-Log) -match 'Done \(') { $done = $true; break }
        Start-Sleep -Seconds 2
    }
    if (-not $done) {
        try { $server.Kill() } catch { }
        throw "[$label] the server never reached Done within $BootTimeoutSeconds seconds"
    }
    Write-Host "[$label] booted"

    # A booted server with nobody on it generates almost nothing - the first run of this compared a
    # single chunk, which proves nothing. Force a real area and give it time to finish. /forceload
    # takes at most 256 chunks per call, so the area is issued in bands.
    # Generation is driven by a datapack load function, written before boot - see New-Datapack.
    # Console commands over stdin were tried first and never reached the command handler: the server
    # accepted `stop` but no forceload ever appeared in the log, and three runs compared worlds that
    # had barely generated. A datapack needs no console and runs at a defined point.
    Write-Host ("[{0}] generating, waiting {1}s" -f $label, $GenerateSeconds)
    Start-Sleep -Seconds $GenerateSeconds

    $stdin.WriteLine('save-all flush')
    Start-Sleep -Seconds 20
    $stdin.WriteLine('stop')
    if (-not $server.WaitForExit(180000)) { try { $server.Kill() } catch { } }

    # A forceload that was rejected is the difference between a real comparison and a fake one, so
    # it is reported rather than assumed.
    $log = Read-Log
    # Vanilla's forceload reply is "Marked N chunk(s) in <dim> to be force loaded". The old pattern
    # here was 'Added .* chunk', which never matched a forceload and DID match mod boot chatter.
    $added = ([regex]::Matches($log, 'to be force loaded')).Count
    $refused = ([regex]::Matches($log, 'Cannot force|too many chunks|Unknown or incomplete command')).Count
    Write-Host ("[{0}] stopped; forceload acks: {1}, refusals: {2}" -f $label, $added, $refused)
    if ($refused -gt 0) { Write-Warning "[$label] the server refused $refused forceload command(s)" }

    # The JVM can outlive WaitForExit by a moment as far as file handles are concerned, and the
    # first run of this script died hashing a region file that was still open. Give Windows a beat
    # and retry rather than failing a run that otherwise completed.
    Start-Sleep -Seconds 5

    $hashes = [ordered] @{}
    # `region` only. `poi` and `entities` are derived indexes that can differ for reasons that say
    # nothing about what terrain was generated, which is the question here.
    foreach ($region in Get-ChildItem -LiteralPath $root -Recurse -Filter '*.mca' -File |
        Where-Object { $_.DirectoryName -match '\\region$' } | Sort-Object FullName) {
        $relative = $region.FullName.Substring($root.Length).TrimStart([char]92)
        $hash = $null
        foreach ($attempt in 1..10) {
            try { $hash = (Get-FileHash -LiteralPath $region.FullName -Algorithm SHA256).Hash; break }
            catch { Start-Sleep -Seconds 2 }
        }
        if (-not $hash) { throw "Could not read $relative - still locked after 20 seconds" }
        $hashes[$relative] = $hash
    }
    return @{ Root = $root; Hashes = $hashes }
}

Write-Host ("seed      {0}" -f $Seed)
$with = Invoke-Run 'with' $(if ($WithholdFromBoth) { $RemoveMods } else { @() })
$without = Invoke-Run 'without' $RemoveMods

Write-Host ''
Write-Host ("regions   {0} with, {1} without" -f $with.Hashes.Count, $without.Hashes.Count)
$all = @($with.Hashes.Keys) + @($without.Hashes.Keys) | Sort-Object -Unique
$differing = @()
$onlyOne = @()
foreach ($key in $all) {
    $a = if ($with.Hashes.Contains($key)) { $with.Hashes[$key] } else { $null }
    $b = if ($without.Hashes.Contains($key)) { $without.Hashes[$key] } else { $null }
    if ($null -eq $a -or $null -eq $b) { $onlyOne += $key; continue }
    if ($a -ne $b) { $differing += $key }
}

Write-Host ''
if ($differing.Count -eq 0 -and $onlyOne.Count -eq 0) {
    Write-Host 'SAME      every region file is byte-identical with and without the withheld mod(s).' -ForegroundColor Green
    Write-Host '          That does NOT clear it: the End is not generated at spawn, and a threading'
    Write-Host '          fault may only appear under load. It is the cheap half of the answer.'
}
else {
    Write-Host ("DIFFERENT {0} region file(s) differ, {1} present in only one run." -f $differing.Count, $onlyOne.Count) -ForegroundColor Yellow
    foreach ($key in ($differing + $onlyOne | Select-Object -First 12)) { Write-Host "  $key" }
    Write-Host ''
    Write-Host '          The withheld mod changes what the same seed generates. For a mod that'
    Write-Host '          promises identical output, that is the finding.'
}

if (-not $KeepDirs) {
    foreach ($run in @($with, $without)) {
        Remove-Item -LiteralPath $run.Root -Recurse -Force -ErrorAction SilentlyContinue
    }
}
else {
    Write-Host ''
    Write-Host ("kept      {0}" -f $with.Root)
    Write-Host ("kept      {0}" -f $without.Root)
}
